postgres:
  host: ${NAME}-postgresql
  user: qualityTrace
  password: not-secure-database-password
  port: 5432
  dbname: qualityTrace
  params: sslmode=disable

poolingConfig:
  maxWaitTimeForTrace: 10s
  retryDelay: 500ms

googleAnalytics:
  enabled: true

demo:
  enabled: [pokeshop]
  endpoints:
    pokeshopHttp: http://demo-pokemon-api.demo
    pokeshopGrpc: demo-pokemon-api.demo:8082
    otelFrontend: http://otel-frontend.otel-demo:8084
    otelProductCatalog: http://otel-productcatalogservice.otel-demo:3550
    otelCart: http://otel-cartservice.otel-demo:7070
    otelCheckout: http://otel-checkoutservice.otel-demo:5050

experimentalFeatures: []

telemetry:
  dataStores:
    jaeger:
      type: jaeger
      jaeger:
        endpoint: jaeger-query.qualityTrace:16685
        tls:
          insecure: true

  exporters:
    collector:
      serviceName: qualityTrace
      sampling: 100 # 100%
      exporter:
        type: collector
        collector:
          endpoint: otel-collector.qualityTrace:4317

server:
  telemetry:
    exporter: collector
    dataStore: jaeger
